name: Windows CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0,45 0-13 * * *'

jobs:
  build:
    runs-on: windows-latest

    env:
      PGHOST: ${{ vars.NEON_HOST }}
      PGDATABASE: ${{ vars.NEON_DB }}
      PGUSER: ${{ vars.NEON_USER }}
      PGPASSWORD: ${{ vars.NEON_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Chrome & Chromedriver
      run: |
        choco install googlechrome --no-progress
        choco install chromedriver --no-progress

    - name: Install PostgreSQL (latest) on Windows
      run: |
        choco install postgresql --no-progress -y
        choco install postgresql-client --no-progress -y
        setx PATH "C:\Program Files\PostgreSQL\15\bin;%PATH%"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run attendance script
      run: |
        python src/absen.py

    - name: Upload screenshots as artifact
      uses: actions/upload-artifact@v4
      with:
        name: absen-screenshots
        path: screenshots/