name: Windows CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Chrome & Chromedriver
      run: |
        choco install googlechrome --no-progress
        choco install chromedriver --no-progress

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run attendance script
      run: |
        python src/absen.py

    - name: Take screenshot
      run: |
        python -m src.utils.screenshot